CampaignManager/Controllers/TagController.cs
using CampaignManager.Models;
using CMBusiness.Services.Concrete;
using MailgunAPIDirect;
using MailgunAPIDirect.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;



namespace CampaignManager.Controllers
{
    public class TagController : Controller
    {
        private List<Tag> listOfTagsFiltered;


        // GET: /Tag/
        [Authorize]
        [HttpGet]
        public ActionResult Index(string id, string tagFilter, string radioId= "", string sortby = "")
        {
            List<Tag> listOfTags=new List<Tag>();
            
            TagService tagService = new TagService();
            if (Session["Tags"] == null)
            {
                listOfTags = tagService.Get();
                Session["Tags"] = listOfTags;
            }
            else
            {
                listOfTags = Session["Tags"] as List<Tag>;
            }
            listOfTagsFiltered = listOfTags;

            if (Session["radioId"] != null && radioId == "" )
            {
                radioId = Session["radioId"].ToString();
            }
            else
            {
                Session["radioId"] = radioId;
            }


            switch (radioId)
            {
                case "rd_last30": listOfTagsFiltered = listOfTags.Where(x => x.first_seen > DateTime.Now.AddDays(-30)).ToList();  break;
                case "rd_last365": listOfTagsFiltered = listOfTags.Where(x => x.first_seen > DateTime.Now.AddDays(-365)).ToList();  break;
                case "all": listOfTagsFiltered = listOfTags.ToList();  break;
            }
            listOfTagsFiltered = listOfTagsFiltered.Where(x => x.first_seen.ToShortDateString() != "01/01/0001").ToList();

            
                if(sortby=="firstseenAZ") listOfTagsFiltered = listOfTagsFiltered.OrderBy(x => x.first_seen).ToList();
                if (sortby == "firstseenZA") listOfTagsFiltered = listOfTagsFiltered.OrderByDescending(x => x.first_seen).ToList();
            if (sortby == "lastseenAZ") listOfTagsFiltered = listOfTagsFiltered.OrderBy(x => x.last_seen).ToList();
            if (sortby == "lastseenZA") listOfTagsFiltered = listOfTagsFiltered.OrderByDescending(x => x.last_seen).ToList();
            if (sortby == "descriptionAZ") listOfTagsFiltered = listOfTagsFiltered.OrderBy(x => x.tag).ToList();
            if (sortby == "descriptionZA") listOfTagsFiltered = listOfTagsFiltered.OrderByDescending(x => x.tag).ToList();

            //foreach (Tag item in listOfTagsFiltered) //get fully tag stats for each tag... this will slow down whole website to load up....
            //{
            //   // EventStats viewModel = tagService.GetTagStats(item.tag, item.first_seen);
            //}


            ViewData["TotalTags"] = "Total Tags showing: " + listOfTagsFiltered.Count;
            if (listOfTagsFiltered.Count >= 1)
            {
                var viewModel = new TagViewModel
                {
                    Tags = listOfTagsFiltered
                };
                return View(viewModel);
            }
            else { ViewBag.Message = "No Campaigns Found."; }
                
            return View();
        }

        // POST: /Tag/Delete/
        [Authorize]
        public ActionResult Delete()
        {
            List<Tag> listOfTags=new List<Tag>();
            if (User.Identity.Name != "CMAdmin@Ez-Runner.com")
            {
                TagService tagService = new TagService();
                if (Session["Tags"] == null)
                {
                    listOfTags = tagService.Get();
                    Session["Tags"] = listOfTags;
                }
                else
                {
                    listOfTags = Session["Tags"] as List<Tag>;
                }


                if (ViewData["tagService"] == null)
                {
                    listOfTags = tagService.Get();
                    ViewData["tagService"] = tagService;
                }
                else
                {
                    tagService = ViewData["tagService"] as TagService;
                }


                

                var viewModel = new TagViewModel
                {
                    Tags = listOfTags

                };
                return View(viewModel);
            }
            return View();
        }


        // POST: /Tag/DeleteTag/?tagID=thetagtodelete
        [Authorize]
        public ActionResult DeleteTag(string id)
        {
            TagService tagService = new TagService();
            Tag theTagWeWant = tagService.Get(id);
            //Call MailgunAPI delete tag method;
            string reponseMessage = tagService.Delete(id);
            return RedirectToAction("Delete");
        }

        // POST: /Tag/GetTagStats/?tagID=theTagId
        [Authorize]
        public ActionResult TagStats(string id,string start, string end)
        {
            
            start = "01/" + start.Substring(3, start.Length - 3);
            GetDaysInMonth(end, ref end);

            ViewData["TagID"] = id;
            DateTime thestartDateWeWant = Convert.ToDateTime(start);
            
            ViewData["startdate"] = start;
            ViewData["enddate"] = end;
            TagService tagService = new TagService();
            EventStats viewModel = tagService.GetTagStats(id, thestartDateWeWant);

            return View(viewModel);
        }

        private string GetDaysInMonth(string end, ref string lastDateofTheMonth)
        {
            string getDaysInAMonth = "31";
            DateTime dtDate = Convert.ToDateTime(end);
            switch (dtDate.Month)
            {
                case 4: case 6: case 9: case 11: getDaysInAMonth = "30"; break;
                case 2: if (dtDate.Year % 4 == 0) getDaysInAMonth = "29"; else getDaysInAMonth = "28"; break;
            }
            lastDateofTheMonth = getDaysInAMonth + dtDate.Month.ToString("/00/") + dtDate.Year.ToString();
            return getDaysInAMonth;
        }
    }
}

CampaignManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <script src="~/Scripts/Ez-runnerSM.js"></script>
    <script src="~/Scripts/Chart.min.js"></script>
    <style>
    </style>

</head>
<body style="background-color: #dee6e6;"  onload="init()">
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse css-sm-tag">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Campaign Explorer</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav menu-item">
        <li><a href="#">@Html.ActionLink("Tags", "Index", "Tag")</a></li>
        @*<li><a href="#">@Html.ActionLink("Remove Tag", "Delete", "Tag")</a></li>*@
        @if (HttpContext.Current.User.Identity.Name == "CMAdmin@Ez-Runner.com")
        {
            <li>@Html.ActionLink("Add Customer Details", "AddCustomerDetails", "Account", routeValues: null, htmlAttributes: new { @class = "nav-spacer" })</li>
                <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-spacer" })</li>
        }
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <li class="login-linkelement">@Html.Partial("_LoginPartial")</li>
    </ul>
</div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        
    </div>
    <div class="container body-content">
        <div class="tag-table-container">
            @RenderBody()
        </div>
    </div>
        <div id="poweredBy">
            Powered by
            <a href="http://www.ez-runner.com/index.php/en/">
                <img id="ctl00_Image1" src="~/images/poweredBy.png">
            </a>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

CampaignManager/Views/Shared/_MessagePartial.cshtml
<h4>@ViewBag.Message</h4>